In [2]:
import pandas as pd
import json
import quandl
from pprint import pprint
from api_key import api_key

In [4]:
state_code = pd.read_csv("State_code_list.csv")
state_code.head()

        State  Code
0  California     1
1       Texas     2
2    New York     3
3     Florida     4
4    Illinois     5

In [5]:
indicator_code = pd.read_csv("indicator_codes_list.csv")
indicator_code.head()

                    INDICATOR     CODE
0   Age of Inventory (Public)     AOIP
1          Buyer Seller Index      BSI
2            Home Sales (NSA)    SALES
3             Home Sales (SA)  SASALES
4  Inventory Measure (Public)      IMP

In [40]:
code_list = ["S26_MPPRSF"]
state_names =[]
median_prices = []
dictionary ={"state": state_names, "median_prices": median_prices}

In [35]:
https://www.quandl.com/api/v3/datasets/ZILLOW/S10_MPPRSF.json?api_key=kTiBuUzNCs2XLbSjUgQ3

SyntaxError: invalid syntax (<ipython-input-35-ca643e28f821>, line 1)

In [36]:
base_url = "https://www.quandl.com/api/v3/datasets/ZILLOW/"

In [42]:
base_url = "https://www.quandl.com/api/v3/datasets/ZILLOW/"
query_url = base_url + code_list[0] + ".csv?api_key=" + api_key 
print(query_url)

https://www.quandl.com/api/v3/datasets/ZILLOW/S26_MPPRSF.csv?api_key=kTiBuUzNCs2XLbSjUgQ3

In [4]:
api_key = 'kTiBuUzNCs2XLbSjUgQ3'
response = base_url + api_key
print(response)

https://www.quandl.com/data/ZILLOW/S28_MSPAH.json?api_key=kTiBuUzNCs2XLbSjUgQ3

In [38]:
for state in code_list:
    query_url = base_url + state + 
    response = requests.get()
    response_dict[response.]
    median_prices.append()

SyntaxError: invalid syntax (<ipython-input-38-0092c4f7d323>, line 1)

In [5]:
data = quandl.get("ZILLOW/S28_MSPAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
data

               Value
Date
1996-04-30   96050.0
1996-05-31   97950.0
1996-06-30   99275.0
1996-07-31  100850.0
1996-08-31  100700.0
...              ...
2016-02-29  167300.0
2016-03-31  170400.0
2016-04-30  178100.0
2016-05-31  186325.0
2016-06-30  197025.0

[243 rows x 1 columns]

In [6]:
data_df = pd.DataFrame(data)
data_df.head()

               Value
Date
1996-04-30   96050.0
1996-05-31   97950.0
1996-06-30   99275.0
1996-07-31  100850.0
1996-08-31  100700.0

In [7]:
pd.set_option('display.max_rows', None)

In [8]:
print(data_df)

                Value
Date
1996-04-30   96050.00
1996-05-31   97950.00
1996-06-30   99275.00
1996-07-31  100850.00
1996-08-31  100700.00
1996-09-30   99800.00
1996-10-31   99650.00
1996-11-30   99850.00
1996-12-31  100000.00
1997-01-31   95000.00
1997-02-28   93500.00
1997-03-31   96150.00
1997-04-30  100425.00
1997-05-31  102975.00
1997-06-30  105600.00
1997-07-31  106475.00
1997-08-31  107650.00
1997-09-30  107950.00
1997-10-31  110075.00
1997-11-30  112400.00
1997-12-31  114200.00
1998-01-31  108350.00
1998-02-28  107950.00
1998-03-31  111050.00
1998-04-30  111575.00
1998-05-31  113175.00
1998-06-30  116750.00
1998-07-31  118250.00
1998-08-31  118800.00
1998-09-30  117850.00
1998-10-31  117300.00
1998-11-30  117000.00
1998-12-31  117000.00
1999-01-31  115500.00
1999-02-28  114950.00
1999-03-31  116350.00
1999-04-30  117800.00
1999-05-31  119175.00
1999-06-30  122275.00
1999-07-31  123000.00
1999-08-31  122375.00
1999-09-30  121400.00
1999-10-31  122075.00
1999-11-30  122200.00
1999-12-31  121400.00
2000-01-31  115475.00
2000-02-29  113575.00
2000-03-31  115900.00
2000-04-30  118750.00
2000-05-31  120850.00
2000-06-30  124200.00
2000-07-31  125250.00
2000-08-31  124050.00
2000-09-30  122875.00
2000-10-31  122250.00
2000-11-30  122075.00
2000-12-31  122250.00
2001-01-31  120925.00
2001-02-28  121700.00
2001-03-31  125225.00
2001-04-30  127425.00
2001-05-31  128575.00
2001-06-30  131850.00
2001-07-31  133100.00
2001-08-31  132550.00
2001-09-30  130975.00
2001-10-31  130225.00
2001-11-30  130000.00
2001-12-31  130750.00
2002-01-31  129775.00
2002-02-28  128700.00
2002-03-31  129825.00
2002-04-30  130725.00
2002-05-31  131825.00
2002-06-30  134775.00
2002-07-31  136250.00
2002-08-31  136900.00
2002-09-30  136675.00
2002-10-31  135575.00
2002-11-30  136050.00
2002-12-31  137625.00
2003-01-31  135200.00
2003-02-28  134050.00
2003-03-31  135950.00
2003-04-30  137075.00
2003-05-31  139225.00
2003-06-30  142400.00
2003-07-31  144400.00
2003-08-31  143250.00
2003-09-30  141275.00
2003-10-31  140225.00
2003-11-30  140250.00
2003-12-31  141675.00
2004-01-31  138125.00
2004-02-29  137100.00
2004-03-31  138225.00
2004-04-30  141125.00
2004-05-31  144050.00
2004-06-30  148300.00
2004-07-31  149925.00
2004-08-31  149225.00
2004-09-30  148300.00
2004-10-31  149000.00
2004-11-30  148700.00
2004-12-31  149300.00
2005-01-31  147200.00
2005-02-28  146750.00
2005-03-31  148200.00
2005-04-30  150050.00
2005-05-31  152850.00
2005-06-30  156900.00
2005-07-31  159250.00
2005-08-31  160000.00
2005-09-30  159500.00
2005-10-31  159650.00
2005-11-30  160350.00
2005-12-31  159850.00
2006-01-31  157300.00
2006-02-28  155600.00
2006-03-31  157500.00
2006-04-30  159250.00
2006-05-31  162500.00
2006-06-30  169250.00
2006-07-31  169500.00
2006-08-31  168700.00
2006-09-30  166350.00
2006-10-31  164450.00
2006-11-30  163800.00
2006-12-31  164350.00
2007-01-31  159850.00
2007-02-28  157500.00
2007-03-31  161700.00
2007-04-30  164500.00
2007-05-31  167550.00
2007-06-30  173075.00
2007-07-31  175725.00
2007-08-31  175800.00
2007-09-30  175150.00
2007-10-31  172500.00
2007-11-30  171750.00
2007-12-31  170700.00
2008-01-31  167800.00
2008-02-29  167250.00
2008-03-31  168550.00
2008-04-30  168700.00
2008-05-31  171300.00
2008-06-30  175100.00
2008-07-31  174900.00
2008-08-31  175250.00
2008-09-30  171050.00
2008-10-31  168850.00
2008-11-30  166350.00
2008-12-31  166700.00
2009-01-31  163125.00
2009-02-28  161524.50
2009-03-31  164077.15
2009-04-30  162797.35
2009-05-31  163250.00
2009-06-30  166735.00
2009-07-31  168100.00
2009-08-31  166100.00
2009-09-30  162800.00
2009-10-31  160700.00
2009-11-30  158900.00
2009-12-31  158800.00
2010-01-31  161800.00
2010-02-28  158900.00
2010-03-31  158850.00
2010-04-30  159750.00
2010-05-31  162350.00
2010-06-30  165550.00
2010-07-31  169100.00
2010-08-31  170075.00
2010-09-30  168425.00
2010-10-31  165700.00
2010-11-30  164700.00
2010-12-31  163000.00
2011-01-31  161425.00
2011-02-28  156800.00
2011-03-31  157550.00
2011-04-30  160500.00
2011-05-31  164950.00
2011-06-30  170500.00
2011-07-31  170975.00
2011-08-31  171500.00
2011-09-30  164000.00
2011-10-31  160800.00
2011-11-30  159200.00
2011-12-31  158975.00
2012-01-31  150075.00
2012-02-29  149550.00
2012-03-31  153850.00
2012-04-30  158150.00
2012-05-31  162700.00
2012-06-30  166925.00
2012-07-31  169325.00
2012-08-31  168000.00
2012-09-30  163500.00
2012-10-31  159250.00
2012-11-30  163475.00
2012-12-31  162200.00
2013-01-31  158500.00
2013-02-28  153600.00
2013-03-31  159200.00
2013-04-30  164510.00
2013-05-31  170440.00
2013-06-30  176300.00
2013-07-31  178750.00
2013-08-31  178000.00
2013-09-30  173800.00
2013-10-31  171200.00
2013-11-30  170000.00
2013-12-31  172000.00
2014-01-31  167225.00
2014-02-28  165700.00
2014-03-31  167200.00
2014-04-30  171500.00
2014-05-31  176750.00
2014-06-30  180500.00
2014-07-31  180550.00
2014-08-31  178600.00
2014-09-30  174800.00
2014-10-31  171750.00
2014-11-30  171550.00
2014-12-31  171875.00
2015-01-31  169575.00
2015-02-28  167250.00
2015-03-31  170650.00
2015-04-30  174900.00
2015-05-31  181125.00
2015-06-30  187300.00
2015-07-31  187350.00
2015-08-31  183475.00
2015-09-30  178750.00
2015-10-31  175496.50
2015-11-30  175727.55
2015-12-31  174018.95
2016-01-31  171750.00
2016-02-29  167300.00
2016-03-31  170400.00
2016-04-30  178100.00
2016-05-31  186325.00
2016-06-30  197025.00

In [9]:
alamance = quandl.get("ZILLOW/CO1292_MVALFAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
alamance

            Value
Date
1996-04-30   53.0
1996-05-31   53.0
1996-06-30   54.0
1996-07-31   54.0
1996-08-31   54.0
1996-09-30   54.0
1996-10-31   55.0
1996-11-30   55.0
1996-12-31   56.0
1997-01-31   56.0
1997-02-28   57.0
1997-03-31   57.0
1997-04-30   58.0
1997-05-31   58.0
1997-06-30   58.0
1997-07-31   59.0
1997-08-31   59.0
1997-09-30   59.0
1997-10-31   60.0
1997-11-30   60.0
1997-12-31   61.0
1998-01-31   61.0
1998-02-28   62.0
1998-03-31   62.0
1998-04-30   63.0
1998-05-31   64.0
1998-06-30   64.0
1998-07-31   65.0
1998-08-31   66.0
1998-09-30   68.0
1998-10-31   68.0
1998-11-30   70.0
1998-12-31   71.0
1999-01-31   72.0
1999-02-28   73.0
1999-03-31   73.0
1999-04-30   74.0
1999-05-31   74.0
1999-06-30   74.0
1999-07-31   74.0
1999-08-31   74.0
1999-09-30   74.0
1999-10-31   73.0
1999-11-30   73.0
1999-12-31   73.0
2000-01-31   73.0
2000-02-29   73.0
2000-03-31   73.0
2000-04-30   72.0
2000-05-31   72.0
2000-06-30   73.0
2000-07-31   74.0
2000-08-31   74.0
2000-09-30   74.0
2000-10-31   75.0
2000-11-30   75.0
2000-12-31   75.0
2001-01-31   75.0
2001-02-28   75.0
2001-03-31   76.0
2001-04-30   76.0
2001-05-31   77.0
2001-06-30   77.0
2001-07-31   77.0
2001-08-31   77.0
2001-09-30   77.0
2001-10-31   76.0
2001-11-30   77.0
2001-12-31   77.0
2002-01-31   77.0
2002-02-28   78.0
2002-03-31   78.0
2002-04-30   78.0
2002-05-31   79.0
2002-06-30   79.0
2002-07-31   79.0
2002-08-31   79.0
2002-09-30   79.0
2002-10-31   80.0
2002-11-30   79.0
2002-12-31   79.0
2003-01-31   79.0
2003-02-28   80.0
2003-03-31   79.0
2003-04-30   79.0
2003-05-31   79.0
2003-06-30   79.0
2003-07-31   79.0
2003-08-31   79.0
2003-09-30   78.0
2003-10-31   78.0
2003-11-30   79.0
2003-12-31   79.0
2004-01-31   80.0
2004-02-29   80.0
2004-03-31   79.0
2004-04-30   79.0
2004-05-31   79.0
2004-06-30   80.0
2004-07-31   80.0
2004-08-31   80.0
2004-09-30   80.0
2004-10-31   80.0
2004-11-30   81.0
2004-12-31   81.0
2005-01-31   82.0
2005-02-28   81.0
2005-03-31   82.0
2005-04-30   82.0
2005-05-31   83.0
2005-06-30   83.0
2005-07-31   84.0
2005-08-31   84.0
2005-09-30   83.0
2005-10-31   84.0
2005-11-30   83.0
2005-12-31   83.0
2006-01-31   82.0
2006-02-28   83.0
2006-03-31   83.0
2006-04-30   84.0
2006-05-31   85.0
2006-06-30   85.0
2006-07-31   86.0
2006-08-31   86.0
2006-09-30   87.0
2006-10-31   87.0
2006-11-30   88.0
2006-12-31   88.0
2007-01-31   88.0
2007-02-28   88.0
2007-03-31   88.0
2007-04-30   87.0
2007-05-31   87.0
2007-06-30   86.0
2007-07-31   86.0
2007-08-31   86.0
2007-09-30   86.0
2007-10-31   86.0
2007-11-30   86.0
2007-12-31   87.0
2008-01-31   87.0
2008-02-29   87.0
2008-03-31   86.0
2008-04-30   85.0
2008-05-31   85.0
2008-06-30   85.0
2008-07-31   84.0
2008-08-31   84.0
2008-09-30   84.0
2008-10-31   84.0
2008-11-30   83.0
2008-12-31   83.0
2009-01-31   83.0
2009-02-28   83.0
2009-03-31   82.0
2009-04-30   82.0
2009-05-31   82.0
2009-06-30   81.0
2009-07-31   81.0
2009-08-31   80.0
2009-09-30   79.0
2009-10-31   79.0
2009-11-30   78.0
2009-12-31   78.0
2010-01-31   78.0
2010-02-28   78.0
2010-03-31   78.0
2010-04-30   78.0
2010-05-31   79.0
2010-06-30   79.0
2010-07-31   79.0
2010-08-31   79.0
2010-09-30   79.0
2010-10-31   79.0
2010-11-30   79.0
2010-12-31   78.0
2011-01-31   78.0
2011-02-28   79.0
2011-03-31   79.0
2011-04-30   80.0
2011-05-31   80.0
2011-06-30   80.0
2011-07-31   79.0
2011-08-31   79.0
2011-09-30   79.0
2011-10-31   78.0
2011-11-30   77.0
2011-12-31   78.0
2012-01-31   78.0
2012-02-29   78.0
2012-03-31   78.0
2012-04-30   78.0
2012-05-31   78.0
2012-06-30   78.0
2012-07-31   78.0
2012-08-31   78.0
2012-09-30   79.0
2012-10-31   79.0
2012-11-30   80.0
2012-12-31   79.0
2013-01-31   79.0
2013-02-28   79.0
2013-03-31   79.0
2013-04-30   78.0
2013-05-31   78.0
2013-06-30   78.0
2013-07-31   78.0
2013-08-31   78.0
2013-09-30   78.0
2013-10-31   78.0
2013-11-30   78.0
2013-12-31   78.0
2014-01-31   78.0
2014-02-28   78.0
2014-03-31   78.0
2014-04-30   78.0
2014-05-31   77.0
2014-06-30   77.0
2014-07-31   76.0
2014-08-31   77.0
2014-09-30   77.0
2014-10-31   77.0
2014-11-30   77.0
2014-12-31   78.0
2015-01-31   79.0
2015-02-28   80.0
2015-03-31   80.0
2015-04-30   80.0
2015-05-31   80.0
2015-06-30   81.0
2015-07-31   81.0
2015-08-31   81.0
2015-09-30   81.0
2015-10-31   82.0
2015-11-30   82.0
2015-12-31   82.0
2016-01-31   82.0
2016-02-29   82.0
2016-03-31   82.0
2016-04-30   82.0
2016-05-31   82.0
2016-06-30   83.0
2016-07-31   83.0
2016-08-31   84.0
2016-09-30   84.0
2016-10-31   85.0
2016-11-30   85.0
2016-12-31   86.0
2017-01-31   86.0
2017-02-28   86.0
2017-03-31   86.0
2017-04-30   87.0
2017-05-31   88.0
2017-06-30   88.0
2017-07-31   88.0
2017-08-31   88.0
2017-09-30   89.0
2017-10-31   90.0
2017-11-30   90.0
2017-12-31   91.0
2018-01-31   91.0
2018-02-28   92.0
2018-03-31   92.0
2018-04-30   93.0
2018-05-31   94.0
2018-06-30   95.0
2018-07-31   95.0
2018-08-31   97.0
2018-09-30   98.0

In [10]:
alexander = quandl.get("ZILLOW/CO721_MVALFAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
alexander

            Value
Date
1996-04-30   49.0
1996-05-31   49.0
1996-06-30   49.0
1996-07-31   50.0
1996-08-31   50.0
1996-09-30   50.0
1996-10-31   51.0
1996-11-30   51.0
1996-12-31   51.0
1997-01-31   51.0
1997-02-28   52.0
1997-03-31   52.0
1997-04-30   53.0
1997-05-31   53.0
1997-06-30   53.0
1997-07-31   54.0
1997-08-31   54.0
1997-09-30   55.0
1997-10-31   55.0
1997-11-30   55.0
1997-12-31   56.0
1998-01-31   56.0
1998-02-28   57.0
1998-03-31   57.0
1998-04-30   57.0
1998-05-31   58.0
1998-06-30   58.0
1998-07-31   58.0
1998-08-31   58.0
1998-09-30   58.0
1998-10-31   58.0
1998-11-30   59.0
1998-12-31   59.0
1999-01-31   59.0
1999-02-28   60.0
1999-03-31   60.0
1999-04-30   61.0
1999-05-31   61.0
1999-06-30   62.0
1999-07-31   62.0
1999-08-31   62.0
1999-09-30   62.0
1999-10-31   62.0
1999-11-30   62.0
1999-12-31   63.0
2000-01-31   63.0
2000-02-29   64.0
2000-03-31   64.0
2000-04-30   64.0
2000-05-31   65.0
2000-06-30   65.0
2000-07-31   65.0
2000-08-31   66.0
2000-09-30   66.0
2000-10-31   67.0
2000-11-30   67.0
2000-12-31   67.0
2001-01-31   68.0
2001-02-28   69.0
2001-03-31   69.0
2001-04-30   69.0
2001-05-31   70.0
2001-06-30   70.0
2001-07-31   70.0
2001-08-31   70.0
2001-09-30   70.0
2001-10-31   70.0
2001-11-30   70.0
2001-12-31   70.0
2002-01-31   70.0
2002-02-28   70.0
2002-03-31   71.0
2002-04-30   71.0
2002-05-31   72.0
2002-06-30   72.0
2002-07-31   72.0
2002-08-31   72.0
2002-09-30   72.0
2002-10-31   72.0
2002-11-30   72.0
2002-12-31   73.0
2003-01-31   73.0
2003-02-28   73.0
2003-03-31   73.0
2003-04-30   73.0
2003-05-31   73.0
2003-06-30   74.0
2003-07-31   74.0
2003-08-31   75.0
2003-09-30   75.0
2003-10-31   76.0
2003-11-30   76.0
2003-12-31   76.0
2004-01-31   76.0
2004-02-29   76.0
2004-03-31   77.0
2004-04-30   77.0
2004-05-31   77.0
2004-06-30   78.0
2004-07-31   78.0
2004-08-31   79.0
2004-09-30   79.0
2004-10-31   80.0
2004-11-30   81.0
2004-12-31   81.0
2005-01-31   82.0
2005-02-28   83.0
2005-03-31   83.0
2005-04-30   84.0
2005-05-31   84.0
2005-06-30   84.0
2005-07-31   85.0
2005-08-31   85.0
2005-09-30   85.0
2005-10-31   86.0
2005-11-30   87.0
2005-12-31   87.0
2006-01-31   87.0
2006-02-28   87.0
2006-03-31   88.0
2006-04-30   88.0
2006-05-31   88.0
2006-06-30   88.0
2006-07-31   88.0
2006-08-31   88.0
2006-09-30   88.0
2006-10-31   88.0
2006-11-30   88.0
2006-12-31   89.0
2007-01-31   90.0
2007-02-28   91.0
2007-03-31   91.0
2007-04-30   92.0
2007-05-31   92.0
2007-06-30   93.0
2007-07-31   93.0
2007-08-31   94.0
2007-09-30   94.0
2007-10-31   94.0
2007-11-30   94.0
2007-12-31   94.0
2008-01-31   94.0
2008-02-29   95.0
2008-03-31   95.0
2008-04-30   96.0
2008-05-31   96.0
2008-06-30   96.0
2008-07-31   96.0
2008-08-31   95.0
2008-09-30   95.0
2008-10-31   95.0
2008-11-30   95.0
2008-12-31   95.0
2009-01-31   94.0
2009-02-28   94.0
2009-03-31   94.0
2009-04-30   94.0
2009-05-31   94.0
2009-06-30   94.0
2009-07-31   93.0
2009-08-31   93.0
2009-09-30   92.0
2009-10-31   92.0
2009-11-30   92.0
2009-12-31   92.0
2010-01-31   92.0
2010-02-28   92.0
2010-03-31   92.0
2010-04-30   92.0
2010-05-31   92.0
2010-06-30   91.0
2010-07-31   91.0
2010-08-31   90.0
2010-09-30   90.0
2010-10-31   89.0
2010-11-30   88.0
2010-12-31   87.0
2011-01-31   86.0
2011-02-28   85.0
2011-03-31   84.0
2011-04-30   83.0
2011-05-31   82.0
2011-06-30   82.0
2011-07-31   83.0
2011-08-31   83.0
2011-09-30   84.0
2011-10-31   84.0
2011-11-30   85.0
2011-12-31   85.0
2012-01-31   85.0
2012-02-29   85.0
2012-03-31   86.0
2012-04-30   86.0
2012-05-31   86.0
2012-06-30   87.0
2012-07-31   87.0
2012-08-31   87.0
2012-09-30   87.0
2012-10-31   87.0
2012-11-30   87.0
2012-12-31   86.0
2013-01-31   86.0
2013-02-28   86.0
2013-03-31   86.0
2013-04-30   85.0
2013-05-31   85.0
2013-06-30   85.0
2013-07-31   85.0
2013-08-31   84.0
2013-09-30   84.0
2013-10-31   84.0
2013-11-30   84.0
2013-12-31   85.0
2014-01-31   86.0
2014-02-28   87.0
2014-03-31   87.0
2014-04-30   87.0
2014-05-31   87.0
2014-06-30   87.0
2014-07-31   87.0
2014-08-31   87.0
2014-09-30   87.0
2014-10-31   87.0
2014-11-30   87.0
2014-12-31   88.0
2015-01-31   88.0
2015-02-28   88.0
2015-03-31   88.0
2015-04-30   88.0
2015-05-31   88.0
2015-06-30   88.0
2015-07-31   87.0
2015-08-31   87.0
2015-09-30   87.0
2015-10-31   88.0
2015-11-30   89.0
2015-12-31   89.0
2016-01-31   89.0
2016-02-29   89.0
2016-03-31   90.0
2016-04-30   90.0
2016-05-31   91.0
2016-06-30   91.0
2016-07-31   92.0
2016-08-31   92.0
2016-09-30   92.0
2016-10-31   91.0
2016-11-30   91.0
2016-12-31   92.0
2017-01-31   92.0
2017-02-28   93.0
2017-03-31   94.0
2017-04-30   95.0
2017-05-31   95.0
2017-06-30   96.0
2017-07-31   96.0
2017-08-31   97.0
2017-09-30   97.0
2017-10-31   98.0
2017-11-30   98.0
2017-12-31   98.0
2018-01-31   98.0
2018-02-28   98.0
2018-03-31   98.0
2018-04-30   98.0
2018-05-31   98.0
2018-06-30   98.0
2018-07-31   99.0
2018-08-31  100.0
2018-09-30  101.0

In [11]:
alleghany = quandl.get("ZILLOW/CO4701_MVALFAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
alleghany

            Value
Date
1999-10-31   67.0
1999-11-30   68.0
1999-12-31   68.0
2000-01-31   69.0
2000-02-29   69.0
2000-03-31   70.0
2000-04-30   70.0
2000-05-31   71.0
2000-06-30   72.0
2000-07-31   72.0
2000-08-31   72.0
2000-09-30   72.0
2000-10-31   73.0
2000-11-30   73.0
2000-12-31   73.0
2001-01-31   74.0
2001-02-28   74.0
2001-03-31   75.0
2001-04-30   75.0
2001-05-31   75.0
2001-06-30   75.0
2001-07-31   76.0
2001-08-31   76.0
2001-09-30   77.0
2001-10-31   77.0
2001-11-30   77.0
2001-12-31   77.0
2002-01-31   77.0
2002-02-28   78.0
2002-03-31   78.0
2002-04-30   78.0
2002-05-31   78.0
2002-06-30   78.0
2002-07-31   79.0
2002-08-31   79.0
2002-09-30   79.0
2002-10-31   80.0
2002-11-30   80.0
2002-12-31   80.0
2003-01-31   80.0
2003-02-28   80.0
2003-03-31   80.0
2003-04-30   81.0
2003-05-31   81.0
2003-06-30   81.0
2003-07-31   81.0
2003-08-31   81.0
2003-09-30   81.0
2003-10-31   81.0
2003-11-30   82.0
2003-12-31   82.0
2004-01-31   83.0
2004-02-29   83.0
2004-03-31   83.0
2004-04-30   84.0
2004-05-31   84.0
2004-06-30   85.0
2004-07-31   85.0
2004-08-31   86.0
2004-09-30   86.0
2004-10-31   87.0
2004-11-30   87.0
2004-12-31   87.0
2005-01-31   88.0
2005-02-28   89.0
2005-03-31   90.0
2005-04-30   90.0
2005-05-31   91.0
2005-06-30   91.0
2005-07-31   92.0
2005-08-31   93.0
2005-09-30   93.0
2005-10-31   94.0
2005-11-30   95.0
2005-12-31   96.0
2006-01-31   96.0
2006-02-28   97.0
2006-03-31   98.0
2006-04-30   98.0
2006-05-31   99.0
2006-06-30  100.0
2006-07-31  101.0
2006-08-31  101.0
2006-09-30  102.0
2006-10-31  102.0
2006-11-30  103.0
2006-12-31  103.0
2007-01-31  104.0
2007-02-28  104.0
2007-03-31  105.0
2007-04-30  106.0
2007-05-31  106.0
2007-06-30  106.0
2007-07-31  106.0
2007-08-31  107.0
2007-09-30  107.0
2007-10-31  108.0
2007-11-30  108.0
2007-12-31  109.0
2008-01-31  109.0
2008-02-29  109.0
2008-03-31  109.0
2008-04-30  109.0
2008-05-31  109.0
2008-06-30  110.0
2008-07-31  110.0
2008-08-31  110.0
2008-09-30  109.0
2008-10-31  109.0
2008-11-30  109.0
2008-12-31  108.0
2009-01-31  108.0
2009-02-28  108.0
2009-03-31  108.0
2009-04-30  108.0
2009-05-31  107.0
2009-06-30  106.0
2009-07-31  105.0
2009-08-31  105.0
2009-09-30  104.0
2009-10-31  104.0
2009-11-30  104.0
2009-12-31  104.0
2010-01-31  103.0
2010-02-28  103.0
2010-03-31  102.0
2010-04-30  102.0
2010-05-31  102.0
2010-06-30  101.0
2010-07-31  101.0
2010-08-31  101.0
2010-09-30  101.0
2010-10-31  101.0
2010-11-30  101.0
2010-12-31  101.0
2011-01-31  101.0
2011-02-28  100.0
2011-03-31  100.0
2011-04-30  100.0
2011-05-31   99.0
2011-06-30   99.0
2011-07-31   99.0
2011-08-31   99.0
2011-09-30   99.0
2011-10-31   99.0
2011-11-30   98.0
2011-12-31   98.0
2012-01-31   97.0
2012-02-29   97.0
2012-03-31   97.0
2012-04-30   97.0
2012-05-31   97.0
2012-06-30   97.0
2012-07-31   97.0
2012-08-31   96.0
2012-09-30   96.0
2012-10-31   96.0
2012-11-30   96.0
2012-12-31   96.0
2013-01-31   96.0
2013-02-28   96.0
2013-03-31   96.0
2013-04-30   96.0
2013-05-31   96.0
2013-06-30   96.0
2013-07-31   96.0
2013-08-31   96.0
2013-09-30   96.0
2013-10-31   96.0
2013-11-30   97.0
2013-12-31   97.0
2014-01-31   97.0
2014-02-28   97.0
2014-03-31   97.0
2014-04-30   98.0
2014-05-31   98.0
2014-06-30   98.0
2014-07-31   98.0
2014-08-31   98.0
2014-09-30   99.0
2014-10-31   99.0
2014-11-30  100.0
2014-12-31  100.0
2015-01-31  100.0
2015-02-28  100.0
2015-03-31  101.0
2015-04-30  101.0
2015-05-31  101.0
2015-06-30  102.0
2015-07-31  102.0
2015-08-31  103.0
2015-09-30  103.0
2015-10-31  104.0
2015-11-30  104.0
2015-12-31  104.0
2016-01-31  104.0
2016-02-29  105.0
2016-03-31  105.0
2016-04-30  105.0
2016-05-31  106.0
2016-06-30  106.0
2016-07-31  106.0
2016-08-31  106.0
2016-09-30  107.0
2016-10-31  107.0
2016-11-30  107.0
2016-12-31  108.0
2017-01-31  108.0
2017-02-28  109.0
2017-03-31  109.0
2017-04-30  110.0
2017-05-31  110.0
2017-06-30  110.0
2017-07-31  110.0
2017-08-31  110.0
2017-09-30  111.0
2017-10-31  111.0
2017-11-30  111.0
2017-12-31  112.0
2018-01-31  113.0
2018-02-28  113.0
2018-03-31  113.0
2018-04-30  114.0
2018-05-31  114.0
2018-06-30  115.0
2018-07-31  115.0
2018-08-31  115.0
2018-09-30  116.0
2018-10-31  116.0
2018-11-30  117.0
2018-12-31  117.0
2019-01-31  117.0
2019-02-28  118.0
2019-03-31  118.0
2019-04-30  118.0
2019-05-31  118.0
2019-06-30  119.0
2019-07-31  119.0
2019-08-31  120.0
2019-09-30  120.0
2019-10-31  120.0
2019-11-30  120.0
2019-12-31  120.0
2020-01-31  121.0
2020-02-29  121.0
2020-03-31  121.0

In [12]:
anson = quandl.get("ZILLOW/CO825_MVALFAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
anson

            Value
Date
1996-04-30   28.0
1996-05-31   27.0
1996-06-30   27.0
1996-07-31   27.0
1996-08-31   27.0
1996-09-30   27.0
1996-10-31   28.0
1996-11-30   28.0
1996-12-31   29.0
1997-01-31   29.0
1997-02-28   29.0
1997-03-31   29.0
1997-04-30   29.0
1997-05-31   29.0
1997-06-30   30.0
1997-07-31   30.0
1997-08-31   30.0
1997-09-30   31.0
1997-10-31   31.0
1997-11-30   32.0
1997-12-31   33.0
1998-01-31   34.0
1998-02-28   34.0
1998-03-31   35.0
1998-04-30   35.0
1998-05-31   36.0
1998-06-30   37.0
1998-07-31   37.0
1998-08-31   38.0
1998-09-30   38.0
1998-10-31   39.0
1998-11-30   39.0
1998-12-31   39.0
1999-01-31   39.0
1999-02-28   39.0
1999-03-31   38.0
1999-04-30   38.0
1999-05-31   39.0
1999-06-30   39.0
1999-07-31   39.0
1999-08-31   39.0
1999-09-30   40.0
1999-10-31   40.0
1999-11-30   40.0
1999-12-31   40.0
2000-01-31   40.0
2000-02-29   40.0
2000-03-31   41.0
2000-04-30   40.0
2000-05-31   41.0
2000-06-30   41.0
2000-07-31   41.0
2000-08-31   41.0
2000-09-30   42.0
2000-10-31   42.0
2000-11-30   42.0
2000-12-31   42.0
2001-01-31   42.0
2001-02-28   42.0
2001-03-31   41.0
2001-04-30   41.0
2001-05-31   41.0
2001-06-30   41.0
2001-07-31   41.0
2001-08-31   41.0
2001-09-30   42.0
2001-10-31   42.0
2001-11-30   42.0
2001-12-31   42.0
2002-01-31   42.0
2002-02-28   42.0
2002-03-31   42.0
2002-04-30   43.0
2002-05-31   42.0
2002-06-30   42.0
2002-07-31   42.0
2002-08-31   42.0
2002-09-30   42.0
2002-10-31   43.0
2002-11-30   43.0
2002-12-31   43.0
2003-01-31   43.0
2003-02-28   43.0
2003-03-31   44.0
2003-04-30   43.0
2003-05-31   43.0
2003-06-30   43.0
2003-07-31   43.0
2003-08-31   43.0
2003-09-30   44.0
2003-10-31   43.0
2003-11-30   43.0
2003-12-31   44.0
2004-01-31   44.0
2004-02-29   45.0
2004-03-31   45.0
2004-04-30   45.0
2004-05-31   46.0
2004-06-30   46.0
2004-07-31   47.0
2004-08-31   48.0
2004-09-30   48.0
2004-10-31   48.0
2004-11-30   49.0
2004-12-31   49.0
2005-01-31   50.0
2005-02-28   50.0
2005-03-31   51.0
2005-04-30   51.0
2005-05-31   52.0
2005-06-30   52.0
2005-07-31   52.0
2005-08-31   53.0
2005-09-30   53.0
2005-10-31   53.0
2005-11-30   54.0
2005-12-31   54.0
2006-01-31   53.0
2006-02-28   53.0
2006-03-31   54.0
2006-04-30   54.0
2006-05-31   54.0
2006-06-30   54.0
2006-07-31   53.0
2006-08-31   54.0
2006-09-30   54.0
2006-10-31   53.0
2006-11-30   53.0
2006-12-31   53.0
2007-01-31   52.0
2007-02-28   52.0
2007-03-31   52.0
2007-04-30   51.0
2007-05-31   52.0
2007-06-30   52.0
2007-07-31   53.0
2007-08-31   53.0
2007-09-30   53.0
2007-10-31   54.0
2007-11-30   55.0
2007-12-31   56.0
2008-01-31   56.0
2008-02-29   57.0
2008-03-31   57.0
2008-04-30   57.0
2008-05-31   57.0
2008-06-30   56.0
2008-07-31   56.0
2008-08-31   55.0
2008-09-30   54.0
2008-10-31   54.0
2008-11-30   53.0
2008-12-31   53.0
2009-01-31   52.0
2009-02-28   52.0
2009-03-31   51.0
2009-04-30   51.0
2009-05-31   50.0
2009-06-30   50.0
2009-07-31   49.0
2009-08-31   50.0
2009-09-30   49.0
2009-10-31   49.0
2009-11-30   49.0
2009-12-31   49.0
2010-01-31   50.0
2010-02-28   49.0
2010-03-31   49.0
2010-04-30   49.0
2010-05-31   49.0
2010-06-30   49.0
2010-07-31   48.0
2010-08-31   47.0
2010-09-30   47.0
2010-10-31   45.0
2010-11-30   44.0
2010-12-31   43.0
2011-01-31   43.0
2011-02-28   42.0
2011-03-31   41.0
2011-04-30   40.0
2011-05-31   40.0
2011-06-30   39.0
2011-07-31   39.0
2011-08-31   39.0
2011-09-30   40.0
2011-10-31   40.0
2011-11-30   41.0
2011-12-31   41.0
2012-01-31   41.0
2012-02-29   42.0
2012-03-31   43.0
2012-04-30   43.0
2012-05-31   44.0
2012-06-30   44.0
2012-07-31   45.0
2012-08-31   46.0
2012-09-30   47.0
2012-10-31   47.0
2012-11-30   47.0
2012-12-31   48.0
2013-01-31   48.0
2013-02-28   48.0
2013-03-31   48.0
2013-04-30   48.0
2013-05-31   48.0
2013-06-30   48.0
2013-07-31   47.0
2013-08-31   47.0
2013-09-30   46.0
2013-10-31   46.0
2013-11-30   45.0
2013-12-31   45.0
2014-01-31   44.0
2014-02-28   44.0
2014-03-31   43.0
2014-04-30   43.0
2014-05-31   43.0
2014-06-30   43.0
2014-07-31   43.0
2014-08-31   43.0
2014-09-30   43.0
2014-10-31   43.0
2014-11-30   44.0
2014-12-31   44.0
2015-01-31   44.0
2015-02-28   44.0
2015-03-31   45.0
2015-04-30   44.0
2015-05-31   45.0
2015-06-30   45.0
2015-07-31   45.0
2015-08-31   45.0
2015-09-30   45.0
2015-10-31   46.0
2015-11-30   46.0
2015-12-31   47.0
2016-01-31   47.0
2016-02-29   47.0
2016-03-31   47.0
2016-04-30   47.0
2016-05-31   47.0
2016-06-30   47.0
2016-07-31   47.0
2016-08-31   47.0
2016-09-30   47.0
2016-10-31   46.0
2016-11-30   46.0
2016-12-31   47.0
2017-01-31   48.0
2017-02-28   48.0
2017-03-31   48.0
2017-04-30   48.0
2017-05-31   48.0
2017-06-30   48.0
2017-07-31   49.0
2017-08-31   49.0
2017-09-30   49.0
2017-10-31   50.0
2017-11-30   49.0
2017-12-31   49.0
2018-01-31   50.0
2018-02-28   51.0
2018-03-31   51.0
2018-04-30   51.0
2018-05-31   51.0
2018-06-30   51.0
2018-07-31   51.0
2018-08-31   51.0
2018-09-30   51.0

In [13]:
ashe = quandl.get("ZILLOW/CO4435_MVALFAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
ashe

            Value
Date
1996-04-30  169.0
1996-05-31  170.0
1996-06-30  171.0
1996-07-31  172.0
1996-08-31  172.0
1996-09-30  172.0
1996-10-31  172.0
1996-11-30  172.0
1996-12-31  172.0
1997-01-31  173.0
1997-02-28  174.0
1997-03-31  175.0
1997-04-30  177.0
1997-05-31  177.0
1997-06-30  178.0
1997-07-31  179.0
1997-08-31  181.0
1997-09-30  182.0
1997-10-31  183.0
1997-11-30  182.0
1997-12-31  182.0
1998-01-31  180.0
1998-02-28  177.0
1998-03-31  174.0
1998-04-30  169.0
1998-05-31  165.0
1998-06-30  160.0
1998-07-31  156.0
1998-08-31  155.0
1998-09-30  156.0
1998-10-31  156.0
1998-11-30  156.0
1998-12-31  156.0
1999-01-31  156.0
1999-02-28  157.0
1999-03-31  160.0
1999-04-30  165.0
1999-05-31  171.0
1999-06-30  174.0
1999-07-31  175.0
1999-08-31  173.0
1999-09-30  171.0
1999-10-31  171.0
1999-11-30  172.0
1999-12-31  172.0
2000-01-31  174.0
2000-02-29  175.0
2000-03-31  174.0
2000-04-30  170.0
2000-05-31  167.0
2000-06-30  167.0
2000-07-31  170.0
2000-08-31  174.0
2000-09-30  176.0
2000-10-31  177.0
2000-11-30  178.0
2000-12-31  180.0
2001-01-31  182.0
2001-02-28  183.0
2001-03-31  185.0
2001-04-30  188.0
2001-05-31  190.0
2001-06-30  191.0
2001-07-31  192.0
2001-08-31  193.0
2001-09-30  194.0
2001-10-31  196.0
2001-11-30  197.0
2001-12-31  197.0
2002-01-31  197.0
2002-02-28  198.0
2002-03-31  199.0
2002-04-30  200.0
2002-05-31  202.0
2002-06-30  204.0
2002-07-31  206.0
2002-08-31  206.0
2002-09-30  207.0
2002-10-31  206.0
2002-11-30  208.0
2002-12-31  209.0
2003-01-31  211.0
2003-02-28  212.0
2003-03-31  213.0
2003-04-30  213.0
2003-05-31  214.0
2003-06-30  214.0
2003-07-31  214.0
2003-08-31  216.0
2003-09-30  217.0
2003-10-31  218.0
2003-11-30  218.0
2003-12-31  219.0
2004-01-31  220.0
2004-02-29  221.0
2004-03-31  223.0
2004-04-30  225.0
2004-05-31  227.0
2004-06-30  227.0
2004-07-31  228.0
2004-08-31  228.0
2004-09-30  228.0
2004-10-31  228.0
2004-11-30  229.0
2004-12-31  231.0
2005-01-31  233.0
2005-02-28  234.0
2005-03-31  235.0
2005-04-30  237.0
2005-05-31  240.0
2005-06-30  245.0
2005-07-31  250.0
2005-08-31  255.0
2005-09-30  260.0
2005-10-31  265.0
2005-11-30  269.0
2005-12-31  273.0
2006-01-31  275.0
2006-02-28  278.0
2006-03-31  280.0
2006-04-30  283.0
2006-05-31  285.0
2006-06-30  287.0
2006-07-31  287.0
2006-08-31  289.0
2006-09-30  290.0
2006-10-31  292.0
2006-11-30  294.0
2006-12-31  296.0
2007-01-31  297.0
2007-02-28  299.0
2007-03-31  301.0
2007-04-30  303.0
2007-05-31  305.0
2007-06-30  306.0
2007-07-31  307.0
2007-08-31  308.0
2007-09-30  309.0
2007-10-31  309.0
2007-11-30  310.0
2007-12-31  311.0
2008-01-31  313.0
2008-02-29  313.0
2008-03-31  313.0
2008-04-30  312.0
2008-05-31  313.0
2008-06-30  314.0
2008-07-31  314.0
2008-08-31  314.0
2008-09-30  313.0
2008-10-31  313.0
2008-11-30  313.0
2008-12-31  312.0
2009-01-31  311.0
2009-02-28  310.0
2009-03-31  309.0
2009-04-30  308.0
2009-05-31  306.0
2009-06-30  304.0
2009-07-31  303.0
2009-08-31  301.0
2009-09-30  300.0
2009-10-31  298.0
2009-11-30  296.0
2009-12-31  295.0
2010-01-31  293.0
2010-02-28  292.0
2010-03-31  291.0
2010-04-30  290.0
2010-05-31  289.0
2010-06-30  289.0
2010-07-31  288.0
2010-08-31  288.0
2010-09-30  287.0
2010-10-31  286.0
2010-11-30  286.0
2010-12-31  285.0
2011-01-31  283.0
2011-02-28  281.0
2011-03-31  279.0
2011-04-30  278.0
2011-05-31  276.0
2011-06-30  276.0
2011-07-31  276.0
2011-08-31  277.0
2011-09-30  277.0
2011-10-31  277.0
2011-11-30  277.0
2011-12-31  277.0
2012-01-31  280.0
2012-02-29  283.0
2012-03-31  286.0
2012-04-30  286.0
2012-05-31  287.0
2012-06-30  288.0
2012-07-31  284.0
2012-08-31  280.0
2012-09-30  276.0
2012-10-31  276.0
2012-11-30  276.0
2012-12-31  276.0
2013-01-31  275.0
2013-02-28  274.0
2013-03-31  274.0
2013-04-30  273.0
2013-05-31  273.0
2013-06-30  273.0
2013-07-31  277.0
2013-08-31  280.0
2013-09-30  283.0
2013-10-31  282.0
2013-11-30  282.0
2013-12-31  282.0
2014-01-31  281.0
2014-02-28  281.0
2014-03-31  280.0
2014-04-30  281.0
2014-05-31  280.0
2014-06-30  280.0
2014-07-31  280.0
2014-08-31  280.0
2014-09-30  281.0
2014-10-31  283.0
2014-11-30  284.0
2014-12-31  284.0
2015-01-31  285.0
2015-02-28  286.0
2015-03-31  288.0
2015-04-30  289.0
2015-05-31  290.0
2015-06-30  291.0
2015-07-31  291.0
2015-08-31  291.0
2015-09-30  291.0
2015-10-31  292.0
2015-11-30  293.0
2015-12-31  294.0
2016-01-31  295.0
2016-02-29  296.0
2016-03-31  296.0
2016-04-30  297.0
2016-05-31  299.0
2016-06-30  300.0
2016-07-31  301.0
2016-08-31  302.0
2016-09-30  303.0
2016-10-31  305.0
2016-11-30  306.0
2016-12-31  307.0
2017-01-31  307.0
2017-02-28  308.0
2017-03-31  308.0
2017-04-30  309.0
2017-05-31  310.0
2017-06-30  311.0
2017-07-31  312.0
2017-08-31  313.0
2017-09-30  314.0
2017-10-31  315.0
2017-11-30  316.0
2017-12-31  318.0
2018-01-31  320.0
2018-02-28  323.0
2018-03-31  326.0
2018-04-30  328.0
2018-05-31  329.0
2018-06-30  331.0
2018-07-31  333.0
2018-08-31  334.0
2018-09-30  335.0
2018-10-31  336.0
2018-11-30  337.0
2018-12-31  339.0
2019-01-31  340.0
2019-02-28  341.0
2019-03-31  342.0
2019-04-30  342.0
2019-05-31  343.0
2019-06-30  344.0
2019-07-31  344.0
2019-08-31  345.0
2019-09-30  345.0
2019-10-31  347.0
2019-11-30  347.0
2019-12-31  348.0
2020-01-31  347.0
2020-02-29  347.0
2020-03-31  348.0

In [15]:
avery = quandl.get("ZILLOW/M24_MVALFAH", authtoken="kTiBuUzNCs2XLbSjUgQ3")
avery

            Value
Date
1996-04-30   88.0
1996-05-31   88.0
1996-06-30   87.0
1996-07-31   87.0
1996-08-31   88.0
1996-09-30   88.0
1996-10-31   88.0
1996-11-30   88.0
1996-12-31   88.0
1997-01-31   88.0
1997-02-28   88.0
1997-03-31   88.0
1997-04-30   88.0
1997-05-31   88.0
1997-06-30   88.0
1997-07-31   88.0
1997-08-31   88.0
1997-09-30   88.0
1997-10-31   88.0
1997-11-30   88.0
1997-12-31   88.0
1998-01-31   89.0
1998-02-28   89.0
1998-03-31   90.0
1998-04-30   90.0
1998-05-31   90.0
1998-06-30   90.0
1998-07-31   90.0
1998-08-31   90.0
1998-09-30   90.0
1998-10-31   90.0
1998-11-30   90.0
1998-12-31   91.0
1999-01-31   91.0
1999-02-28   91.0
1999-03-31   91.0
1999-04-30   91.0
1999-05-31   92.0
1999-06-30   93.0
1999-07-31   93.0
1999-08-31   93.0
1999-09-30   94.0
1999-10-31   94.0
1999-11-30   94.0
1999-12-31   95.0
2000-01-31   95.0
2000-02-29   95.0
2000-03-31   95.0
2000-04-30   95.0
2000-05-31   95.0
2000-06-30   94.0
2000-07-31   93.0
2000-08-31   93.0
2000-09-30   93.0
2000-10-31   93.0
2000-11-30   93.0
2000-12-31   93.0
2001-01-31   93.0
2001-02-28   93.0
2001-03-31   93.0
2001-04-30   92.0
2001-05-31   92.0
2001-06-30   92.0
2001-07-31   92.0
2001-08-31   92.0
2001-09-30   92.0
2001-10-31   92.0
2001-11-30   92.0
2001-12-31   92.0
2002-01-31   92.0
2002-02-28   92.0
2002-03-31   92.0
2002-04-30   93.0
2002-05-31   93.0
2002-06-30   93.0
2002-07-31   94.0
2002-08-31   94.0
2002-09-30   94.0
2002-10-31   95.0
2002-11-30   95.0
2002-12-31   96.0
2003-01-31   96.0
2003-02-28   96.0
2003-03-31   95.0
2003-04-30   95.0
2003-05-31   96.0
2003-06-30   96.0
2003-07-31   96.0
2003-08-31   97.0
2003-09-30   97.0
2003-10-31   97.0
2003-11-30   97.0
2003-12-31   98.0
2004-01-31   99.0
2004-02-29  100.0
2004-03-31  101.0
2004-04-30  102.0
2004-05-31  103.0
2004-06-30  104.0
2004-07-31  104.0
2004-08-31  105.0
2004-09-30  106.0
2004-10-31  106.0
2004-11-30  107.0
2004-12-31  107.0
2005-01-31  108.0
2005-02-28  108.0
2005-03-31  108.0
2005-04-30  109.0
2005-05-31  109.0
2005-06-30  109.0
2005-07-31  110.0
2005-08-31  110.0
2005-09-30  110.0
2005-10-31  111.0
2005-11-30  111.0
2005-12-31  111.0
2006-01-31  111.0
2006-02-28  112.0
2006-03-31  113.0
2006-04-30  113.0
2006-05-31  114.0
2006-06-30  114.0
2006-07-31  115.0
2006-08-31  116.0
2006-09-30  117.0
2006-10-31  117.0
2006-11-30  118.0
2006-12-31  119.0
2007-01-31  120.0
2007-02-28  120.0
2007-03-31  120.0
2007-04-30  121.0
2007-05-31  121.0
2007-06-30  122.0
2007-07-31  123.0
2007-08-31  124.0
2007-09-30  124.0
2007-10-31  125.0
2007-11-30  125.0
2007-12-31  125.0
2008-01-31  125.0
2008-02-29  125.0
2008-03-31  125.0
2008-04-30  125.0
2008-05-31  125.0
2008-06-30  125.0
2008-07-31  124.0
2008-08-31  124.0
2008-09-30  123.0
2008-10-31  123.0
2008-11-30  122.0
2008-12-31  122.0
2009-01-31  122.0
2009-02-28  121.0
2009-03-31  121.0
2009-04-30  121.0
2009-05-31  120.0
2009-06-30  120.0
2009-07-31  120.0
2009-08-31  119.0
2009-09-30  119.0
2009-10-31  119.0
2009-11-30  119.0
2009-12-31  119.0
2010-01-31  119.0
2010-02-28  119.0
2010-03-31  119.0
2010-04-30  119.0
2010-05-31  119.0
2010-06-30  119.0
2010-07-31  119.0
2010-08-31  119.0
2010-09-30  119.0
2010-10-31  119.0
2010-11-30  118.0
2010-12-31  117.0
2011-01-31  117.0
2011-02-28  117.0
2011-03-31  116.0
2011-04-30  116.0
2011-05-31  115.0
2011-06-30  115.0
2011-07-31  114.0
2011-08-31  114.0
2011-09-30  114.0
2011-10-31  114.0
2011-11-30  114.0
2011-12-31  114.0
2012-01-31  114.0
2012-02-29  114.0
2012-03-31  114.0
2012-04-30  115.0
2012-05-31  115.0
2012-06-30  116.0
2012-07-31  116.0
2012-08-31  116.0
2012-09-30  116.0
2012-10-31  116.0
2012-11-30  116.0
2012-12-31  117.0
2013-01-31  118.0
2013-02-28  118.0
2013-03-31  118.0
2013-04-30  118.0
2013-05-31  119.0
2013-06-30  119.0
2013-07-31  120.0
2013-08-31  121.0
2013-09-30  122.0
2013-10-31  123.0
2013-11-30  123.0
2013-12-31  123.0
2014-01-31  124.0
2014-02-28  125.0
2014-03-31  125.0
2014-04-30  126.0
2014-05-31  127.0
2014-06-30  127.0
2014-07-31  128.0
2014-08-31  128.0
2014-09-30  128.0
2014-10-31  129.0
2014-11-30  130.0
2014-12-31  131.0
2015-01-31  131.0
2015-02-28  132.0
2015-03-31  133.0
2015-04-30  134.0
2015-05-31  134.0
2015-06-30  135.0
2015-07-31  135.0
2015-08-31  137.0
2015-09-30  138.0
2015-10-31  138.0
2015-11-30  139.0
2015-12-31  140.0
2016-01-31  140.0
2016-02-29  141.0
2016-03-31  141.0
2016-04-30  142.0
2016-05-31  143.0
2016-06-30  144.0
2016-07-31  144.0
2016-08-31  145.0
2016-09-30  145.0
2016-10-31  146.0
2016-11-30  146.0
2016-12-31  147.0
2017-01-31  149.0
2017-02-28  150.0
2017-03-31  151.0
2017-04-30  151.0
2017-05-31  152.0
2017-06-30  152.0
2017-07-31  153.0
2017-08-31  154.0
2017-09-30  155.0
2017-10-31  156.0
2017-11-30  156.0
2017-12-31  157.0
2018-01-31  157.0
2018-02-28  157.0
2018-03-31  158.0
2018-04-30  159.0
2018-05-31  160.0
2018-06-30  160.0
2018-07-31  161.0
2018-08-31  162.0
2018-09-30  162.0
2018-10-31  163.0
2018-11-30  163.0
2018-12-31  164.0
2019-01-31  165.0
2019-02-28  166.0
2019-03-31  166.0
2019-04-30  167.0
2019-05-31  167.0
2019-06-30  168.0
2019-07-31  168.0
2019-08-31  169.0
2019-09-30  170.0
2019-10-31  170.0
2019-11-30  171.0
2019-12-31  171.0
2020-01-31  171.0
2020-02-29  171.0
2020-03-31  172.0